name: 'Continuous integration'
on: ['push', 'pull_request']
jobs:
  phpunit:
    runs-on: 'ubuntu-20.04'
    name: 'PHPUnit (PHP ${{ matrix.php }}, ES ${{ matrix.elasticsearch }})'
    timeout-minutes: 10
    env:
      SYMFONY_REQUIRE: "${{ matrix.symfony_require }}"
    strategy:
      matrix:
        include:
          - php: '8.1'
            elasticsearch: '6.8.23'
            dependencies: 'highest'
            symfony_require: '4.4.*'
      fail-fast: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          coverage: 'none'
          tools: 'pecl, composer:v2, flex'
          extensions: 'curl, json, mbstring, mongodb, openssl'

      - name: "Install Composer dependencies (${{ matrix.dependencies }})"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --prefer-stable"

      - name: 'Setup Elasticsearch'
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
          docker network create elastic
          docker run -d --name=elasticsearch --network=elastic -p 9200:9200 -e discovery.type=single-node -e node.name=es docker.elastic.co/elasticsearch/elasticsearch:${{ matrix.elasticsearch }} sh -c "./bin/elasticsearch-plugin install --batch ingest-attachment && /usr/local/bin/docker-entrypoint.sh"
          docker run --rm --network=elastic curlimages/curl --max-time 120 --retry-max-time 120 --retry 120 --retry-delay 5 --retry-all-errors --show-error --silent http://elasticsearch:9200
      - name: 'Run unit tests'
        run: |
          vendor/bin/phpunit
